meters/urls.py
from django.conf.urls import url

from . import views

app_name = 'meters'
urlpatterns = [
    # ex: /meters/ основная страница
    url(r'^$', views.index, name = 'index'),
    # ex: /meters/addmetersdata основная страница
    url(r'^addmetersdata/$', views.AddMetersDataView.as_view(), name = 'addmetersdata'),
    url(r'^changemeter/(?P<meter_id>[0-9]+)/$', views.get_change_meter, name = 'getchangemeter'),
    url(r'^deletemeter/(?P<meter_id>[0-9]+)/$', views.delete_meter, name = 'deletemeter'),
    url(r'^texttosend/$', views.get_text_to_send, name = 'texttosend'),
]

myfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^table/', include('table.urls')),
    url(r'^meters/', include('meters.urls')),
    url(r'^admin/', admin.site.urls),
]

table/urls.py
from django.conf.urls import url

from . import views

app_name = 'table'
urlpatterns = [
    # ex: /table/main основная страница
    url(r'^$', views.main, name = 'main'),
     # ex: /table/auth_login/ аутентификация
    url(r'^auth_login/$', views.auth_login, name='auth_login'),
     # ex: /table/auth_logout/ выход из системы
    url(r'^auth_logout/$', views.auth_logout, name='auth_logout'),
    # ex: /table/costlist/   таблица расходов за текущий месяц
    url(r'^costslist/$', views.current_month_expenses, name = 'current_month_expenses'),
    url(r'^deletecost/(?P<cost_id>[0-9]+)/$', views.delete_cost, name = 'deletecost'),
    # ex: /table/addcost/   добавить расход
    url(r'^addcost/$', views.AddCostView.as_view(), name = 'addcost'),
    # ex: /table/costsample/   поиск по расходам
    url(r'^costssample/$', views.get_costs_sample, name = 'costssample'),
    # ex: /table/costsample/2 редактирование существующего расхода
    url(r'^costssample/(?P<cost_id>[0-9]+)/$', views.get_change_cost, name = 'getchangecost'),
    # ex: /table/typeofcosts/ типы расходов
    url(r'^typeofcosts/$', views.AddTypeOfCostView.as_view(), name = 'typeofcost'),
    
]

table/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone

# Create your models here.
def getnow():
    return timezone.now()

class Typeofbuy(models.Model): #create table Typeofbuy (tip pokupki)
    typeofbuy_text = models.CharField(max_length = 200, verbose_name = 'Тип расхода')
    def __str__(self):
    	return self.typeofbuy_text
    def get_absolute_url(self):
        return reverse ('table:typeofcost', )

class Costs(models.Model): #create table Costs (rasxody)
    date_buy = models.DateTimeField(verbose_name = 'Дата покупки', default = getnow , help_text = 'гггг-мм-дд')
    summa_buy = models.DecimalField(max_digits = 9, decimal_places = 2, verbose_name = 'Сумма покупки')
    type_of_buy = models.ForeignKey(Typeofbuy, on_delete = models.CASCADE, verbose_name = 'Тип покупки') #eto id typeofbuy
    note = models.CharField(max_length = 200, verbose_name = 'Примечание', blank = True)
    class Meta:
        ordering = ["-date_buy"]
    def get_absolute_url(self):
        return reverse ('table:addcost', )

class Typeofincome(models.Model): #create table Typeofincome (tip doxoda)
    typeofincome_text = models.CharField(max_length = 200)   
    def __str__(self):
    	return self.typeofincome_text
    def get_absolute_url(self):
        return reverse ('table:typeofcost', )

class Incomes(models.Model): #create table Incomes (doxody)
    date_income = models.DateTimeField()
    summa_income = models.DecimalField(max_digits = 9, decimal_places = 2)
    type_of_income = models.ForeignKey(Typeofincome, on_delete = models.CASCADE) #eto id typeofbuy
    note = models.CharField(max_length = 200)

table/forms.py
import datetime
from django import forms
from .models import Costs, Typeofbuy
from django.forms import ModelForm, Form
from django.utils import timezone
from datetime import date

class LoginForm(forms.Form):
    username = forms.CharField(label="Имя пользователя", max_length=256, required=True)
    password = forms.CharField(label="Пароль", max_length=256, widget=forms.PasswordInput, required=True)
    
class CostsForm(ModelForm): #создание формы из модели
	class Meta:
		model = Costs
		fields = ['date_buy', 'type_of_buy', 'summa_buy', 'note']
		error_css_class = 'error'
		required_css_class = 'required'

class InputDateForm(Form): # создание формы вручную
	from_date = forms.DateTimeField(label = 'Введите начальную дату', help_text = 'гггг-мм-дд', initial = datetime.date(timezone.now().year, timezone.now().month, 1))
	due_date = forms.DateTimeField(label = 'Введите конечную дату', help_text = 'гггг-мм-дд', initial = timezone.now())
	error_css_class = 'error'
	required_css_class = 'required'

class TypeOfCostsForm(ModelForm):
	class Meta:
		model = Typeofbuy
		fields = ['typeofbuy_text']
		error_css_class = 'error'
		required_css_class = 'required'

table/views.py
from django.shortcuts import get_list_or_404, render, get_object_or_404
import datetime
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import *
from django.db import connection #модуль для обращения напрямую к БД
from django.utils import timezone
from django.views import generic
from .forms import CostsForm, InputDateForm, TypeOfCostsForm, LoginForm
from datetime import date, timedelta
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout

#Создание строки даты для запроса SQL
def make_date_query_string(date):
	#return "'" + unicode(date.strftime('%Y%m%d')) + "' "
	return "'" + date.strftime('%Y-%m-%d') + "' "

def main(request):
	form = LoginForm()
	context = {'form' : form} 
	return render(request, 'table/main.html', context)

def auth_login(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			return HttpResponseRedirect(reverse('table:main', ))
		else:
			form = LoginForm()
			context = {'form' : form, 'error': "Пользователь не активен (закончился срок регистрации)"} 
			return render(request, 'table/main.html', context)
	else:
		form = LoginForm()
		context = {'form' : form, 'error': "Неверно введены имя пользователя или пароль. Попробуйте снова."} 
		return render(request, 'table/main.html', context)

def auth_logout(request):
	logout(request)
	return HttpResponseRedirect("/table/")    


@login_required(login_url='/table/')
def current_month_expenses(request): # расходы за текущий месяц
	current_day = timezone.now().day
	current_month = timezone.now().month 
	current_year = timezone.now().year
	day = timedelta(days = 1)
	
	# запрос напрямую к БД
	with connection.cursor() as cursor:#используется менеджер контекста для закрытия соединения с БД без написания .close()
		sql = '''
		SELECT SUM (summa_buy)
		FROM table_costs
		WHERE date_buy >= {from_date} AND  date_buy <= {due_date}
		'''.format(
			from_date=make_date_query_string(datetime.date(current_year,current_month,1)),
			due_date=make_date_query_string(timezone.now() + day),
			)
		cursor.execute(sql)
		total_sum = cursor.fetchone()

	# запрос через manager django
	top_costs = Costs.objects.filter(date_buy__year = current_year, date_buy__month = current_month)
	context = {'top_costs': top_costs, 'total_sum' : total_sum[0]}
	return render(request, 'table/lastcosts.html', context)

class AddCostView(LoginRequiredMixin, PermissionRequiredMixin, generic.edit.CreateView): # добавление нового расхода по ссылке главного меню
	model = Costs
	fields = ['date_buy', 'type_of_buy', 'summa_buy', 'note']
	template_name = 'table/addcost.html'
	login_url = '/table/'
	permission_required = 'table.add_costs'
	#url для редиректа определен в модели
	
#@login_required(login_url='/table/')
class AddTypeOfCostView(LoginRequiredMixin, PermissionRequiredMixin, generic.edit.CreateView): # добавление нового  типа расхода по ссылке главного меню
	model = Typeofbuy
	fields = ['typeofbuy_text']
	template_name = 'table/typeofcost.html'
	def get_context_data(self, **kwargs):
		context = super(AddTypeOfCostView, self).get_context_data(**kwargs)
		context['all_types'] = Typeofbuy.objects.order_by('typeofbuy_text')
		return context
	login_url = '/table/'
	permission_required = 'table.add_typeofincome'
	#url для редиректа определен в модели 

'''def get_delete_or_change_type_of_cost(request): # изменение или удаление типа расхода 
	all_types = Typeofbuy.objects.order_by('typeofbuy_text')
	if request.method == 'POST':
		form = TypeOfCostsForm(request.POST)
		form.save() 
	else:
		form = TypeOfCostsForm() 
	context = {'form' : form, 'all_types':all_types if all_types else None}
	return render(request, 'table/typeofcost.html', context)
'''
@login_required(login_url='/table/')
def get_costs_sample(request): # выборка расходов по датам
	costs_sample_list = []
	from_date = datetime.date(timezone.now().year,1,1)
	day = timedelta(days = 1)
	due_date = timezone.now()


	if request.method == 'POST':
		form = InputDateForm(request.POST)
		if form.is_valid():
			from_date = form.cleaned_data['from_date']
			due_date = form.cleaned_data['due_date']
			costs_sample_list = Costs.objects.filter(date_buy__range = (from_date, due_date + day))
	else:
		form = InputDateForm()
	#подсчет суммы расходов по выборке
	with connection.cursor() as cursor:#используется менеджер контекста для закрытия соединения с БД без написания .close()
		sql = '''
		SELECT SUM (summa_buy)
		FROM table_costs
		WHERE date_buy >= {from_date} AND date_buy <= {due_date}
		'''.format(
			from_date=make_date_query_string(from_date),
			due_date=make_date_query_string(due_date + day),
			)
		cursor.execute(sql)
		total_sum = cursor.fetchone()

	context = {'form' : form, 'costs_sample_list': costs_sample_list if costs_sample_list else None, 'from_date' : from_date, 'due_date' : due_date, 'total_sum' : total_sum[0]}
	return render(request, 'table/costssample.html', context)
	print(due_date)

@permission_required('table.change_costs', login_url='/table/')
@login_required(login_url='/table/')
def get_change_cost(request, cost_id): # изменение конкретного существующего расхода по ссылке из таблицы
	cost = get_object_or_404(Costs, pk = cost_id)
	if request.method == 'POST':
		form = CostsForm(request.POST, instance = cost) # связывание данных формы с данными конкретного экземпляра модели  (изменение)
		form.save() 
		return HttpResponseRedirect(reverse('table:current_month_expenses', ))
	else:
		form = CostsForm(instance = cost) # создание формы для изменения существующего расхода
		context = {'form' : form}
		return render(request, 'table/addcost.html', context)

@login_required(login_url='/table/')
def delete_cost(request, cost_id):
	cost = get_object_or_404(Costs, pk = cost_id)
	cost.delete()
	return HttpResponseRedirect(reverse('table:current_month_expenses', ))

table/templates/table/addcost.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>Информация о расходе</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>

<a href="{% url 'table:current_month_expenses' %}">Вернуться к финансам</a></br></br>
<form action="" method="post">
{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Сохранить" /> 
</form>

table/templates/table/costs_form.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>Добавить новый раcход</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>


<form action="" method="post">
{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Сохранить" /> 
</form>

table/templates/table/costssample.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>ФИНАНСЫ. Выборка расходов по параметрам.</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>


<a href="{% url 'table:main' %}">На главную</a></br></br>
<a href="{% url 'table:addcost' %}">Добавить расходы</a></br></br>
<a href="{% url 'table:typeofcost' %}">Добавить новый тип расхода</a></br></br>
<a href="{% url 'table:costssample' %}">Сделать выборку расходов</a></br></br>
<<h1>Введите параметры поиска</h1>

<form action="" method="post">
{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Вывести список" /> 
</form>
{% if costs_sample_list %}
	<table border="1" width="50%">
	<caption><b>Таблица расходов за период c {{from_date|date:"d.m.Y"}} по {{due_date|date:"d.m.Y"}}</b></caption>
		<tr>
			<th>Дата</th>
			<th>Тип расхода</th>
			<th>Сумма</th>
			<th>Примечание</th>
			<th></th>
		</tr>
		{% for cost in costs_sample_list %}
		<tr>
			<td><a href="{% url 'table:getchangecost' cost.id %}">{{cost.date_buy|date:"d.m.Y"}}</a></td>
			<td>{{cost.type_of_buy}}</td>
			<td>{{cost.summa_buy}}</td>
			<td>{{cost.note}}</td>
			<td bordercolor="white"><a href="{% url 'table:deletecost' cost.id %}">Удалить</a></td>
		</tr>
		{% endfor %} 
	</table>
	<div><b>ИТОГО: {{total_sum}} руб.</b></div>
{% endif %}

table/templates/table/index.html
{% if cost_list %}
    <ul>
    {% for el in cost_list %}
        <li>{{ el }}</li>   
    {% endfor %}
    </ul>
{% else %}
    <p>No table are available.</p>
{% endif %}

table/templates/table/inputdate.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <h1>Введите параметры поиска ляяяя</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>


<form action="" method="post">
{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Вывести список" /> 
</form>

table/templates/table/lastcosts.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>ФИНАНСЫ</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>


<a href="{% url 'table:main' %}">На главную</a></br></br>
<a href="{% url 'table:addcost' %}">Добавить расходы</a></br></br>
<a href="{% url 'table:typeofcost' %}">Добавить новый тип расхода</a></br></br>
<a href="{% url 'table:costssample' %}">Сделать выборку расходов</a></br></br>
<table border="1" width="50%">
<caption><b>Таблица расходов за последний месяц</b></caption>
	<tr>
		<th>Дата</th>
		<th>Тип расхода</th>
		<th>Сумма</th>
		<th>Примечание</th>
		<th></th>
	</tr>
	{% for cost in top_costs %}
	<tr>
		<td><a href="{% url 'table:getchangecost' cost.id %}">{{cost.date_buy|date:"d.m.Y"}}</a></td>
		<td>{{cost.type_of_buy}}</td>
		<td>{{cost.summa_buy}}</td>
		<td>{{cost.note}}</td>
		<td bordercolor="white"><a href="{% url 'table:deletecost' cost.id %}">Удалить</a></td>
	</tr>
	{% endfor %} 
</table>
<div><b>ИТОГО: {{total_sum}} руб.</b></div>

table/templates/table/main.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>ПРОЕКТ ПРИЛОЖЕНИЯ ДЛЯ УЧЕТА ФИНАНСОВ</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>


{% if not user.is_authenticated %}        

        {% if form %}

        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <form class="filter-form do-not-print round-bordered form-panel" action="{% url 'table:auth_login' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-xs-12">
                                <h4 class="do-not-print">Для входа в систему введите имя пользователя и пароль</h4>
                            </div>
                        </div>
                        {{ form.non_field_errors }}
                        <div class="row">
                            {{ form.subject.errors }}
                            <div class="col-lg-4">
                                <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            </div>
                            <div class="col-lg-8">{{ form.username }}</div>
                        </div>
                        <div class="row">
                            {{ form.password.errors }}
                            <div class="col-lg-4">
                                <label for="{{ form.password.id_for_label }}">Пароль</label>
                            </div>
                            <div class="col-lg-8">{{ form.password }}</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <input class="btn btn-default" type="submit" value="Войти в систему" />
                            </div>
                        </div>
                        {% if error %}
                            <div class="alert alert-danger" role="alert">
                                <span>{{ error }}</span>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
	
{% else %}

	<a href="{% url 'table:current_month_expenses' %}">УЧЕТ ФИНАНСОВ</a></br></br>
	<a href="{% url 'meters:index' %}">ПОКАЗАНИЯ СЧЕТЧИКОВ </a></br></br>
{% endif %}

table/templates/table/t.html
<p><b>Дата покупки: </b><br>
 <input type="datetime" name="html_date_buy" value = {{datebuy|date:"d/m/Y/H:m:s"}}>	
</p>
<p><b>Наименование покупки:</b><br>
<p><select name="html_type_of_buy" size="3">
    {% for cost in costs.typeofbuy_set.all %}
        <option value= "html_type_of_buy" + str(forloop.counter)>{{costs.typeofbuy_text}}</option>
    {% endfor %} 
   </select>
</p>
<p><b>Сумма покупки:</b><br>
 <input type="text" name = "html_summa_buy" size="40">
 </p> 
<p><b>Примечание:</b><Br>
 <textarea name="html_note" cols="40" rows="3"></textarea></p>

table/templates/table/typeofcost.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>Добавить новый тип раcхода</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>

<a href="{% url 'table:current_month_expenses' %}">Вернуться к финансам</a></br></br>
<form action="" method="post">
{% csrf_token %}
    {{ form.as_p }}
<input type="submit" name = "Save" value="Сохранить"> 
<input type="button" name = "Delete" value="Удалить"> 
</form>
{% if all_types %}
	<p> Типы расходов: </p>
	{% for type in all_types %}
		<ul>
			<li>{{type.typeofbuy_text}}</li>
		</ul>
	{% endfor %}
{% endif %}