meters/urls.py
from django.conf.urls import url

from . import views

app_name = 'meters'
urlpatterns = [
    # ex: /meters/ основная страница
    url(r'^$', views.index, name = 'index'),
    # ex: /meters/addmetersdata основная страница
    url(r'^addmetersdata/$', views.AddMetersDataView.as_view(), name = 'addmetersdata'),
    url(r'^changemeter/(?P<meter_id>[0-9]+)/$', views.get_change_meter, name = 'getchangemeter'),
    url(r'^deletemeter/(?P<meter_id>[0-9]+)/$', views.delete_meter, name = 'deletemeter'),
    url(r'^texttosend/$', views.get_text_to_send, name = 'texttosend'),
]

myfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^table/', include('table.urls')),
    url(r'^meters/', include('meters.urls')),
    url(r'^admin/', admin.site.urls),
]

table/urls.py
from django.conf.urls import url

from . import views

app_name = 'table'
urlpatterns = [
    # ex: /table/main основная страница
    url(r'^$', views.main, name = 'main'),
     # ex: /table/auth_login/ аутентификация
    url(r'^auth_login/$', views.auth_login, name='auth_login'),
     # ex: /table/auth_logout/ выход из системы
    url(r'^auth_logout/$', views.auth_logout, name='auth_logout'),
    # ex: /table/costlist/   таблица расходов за текущий месяц
    url(r'^costslist/$', views.current_month_expenses, name = 'current_month_expenses'),
    url(r'^deletecost/(?P<cost_id>[0-9]+)/$', views.delete_cost, name = 'deletecost'),
    # ex: /table/addcost/   добавить расход
    url(r'^addcost/$', views.AddCostView.as_view(), name = 'addcost'),
    # ex: /table/costsample/   поиск по расходам
    url(r'^costssample/$', views.get_costs_sample, name = 'costssample'),
    # ex: /table/costsample/2 редактирование существующего расхода
    url(r'^costssample/(?P<cost_id>[0-9]+)/$', views.get_change_cost, name = 'getchangecost'),
    # ex: /table/typeofcosts/ типы расходов
    url(r'^typeofcosts/$', views.AddTypeOfCostView.as_view(), name = 'typeofcost'),
    
]

meters/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


# Create your models here.
def getnow():
    return timezone.now()

class MetersData(models.Model):
	date_meter = models.DateField(verbose_name = 'Дата снятия показаний', default = getnow)
	cold_water = models.DecimalField(max_digits = 10, decimal_places = 3, verbose_name = 'Холодная вода')
	hot_water = models.DecimalField(max_digits = 10, decimal_places = 3, verbose_name = 'Горячая вода')
	electricity_apartment = models.DecimalField(max_digits = 10, decimal_places = 3, verbose_name = 'Электричество в квартире')
	electricity_storeroom = models.DecimalField(max_digits = 10, decimal_places = 3, verbose_name = 'Электричество в подсобном помещении')
	note = models.CharField(max_length = 200, verbose_name = 'Примечание', blank = True)
	class Meta:
		ordering = ["-date_meter"]
	def get_absolute_url(self):
		return reverse ('meters:index', )

meters/forms.py
import datetime
from django import forms
from .models import MetersData
from django.forms import ModelForm
from django.utils import timezone
from datetime import date

class MetersForm(ModelForm): #создание формы из модели
	class Meta:
		model = MetersData
		fields = ['date_meter', 'cold_water', 'hot_water', 'electricity_apartment', 'electricity_storeroom', 'note']
		error_css_class = 'error'
		required_css_class = 'required'

meters/views.py
from django.shortcuts import render
from django.views import generic
from django.db import connection #модуль для обращения напрямую к БД
from django.shortcuts import get_list_or_404, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import *
from .forms import *

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

@login_required(login_url='/table/')
def index(request):
	current_year = timezone.now().year
	# запрос через manager django
	meters_current_year = MetersData.objects.filter(date_meter__year = current_year)
	context = {'meters_current_year': meters_current_year}
	return render(request, 'meters/meterscurrentyear.html', context)

class AddMetersDataView(LoginRequiredMixin, PermissionRequiredMixin, generic.edit.CreateView): # добавление нового расхода по ссылке главного меню
	model = MetersData
	fields = ['date_meter', 'cold_water', 'hot_water', 'electricity_apartment', 'electricity_storeroom', 'note']
	template_name = 'meters/addmetersdata.html'
	login_url = '/table/'
	permission_required = 'meter.add_metersdata'
	#url для редиректа определен в модели

@permission_required('meter.change_metersdata', login_url='/table/')
@login_required(login_url='/table/')
def get_change_meter(request, meter_id): # изменение конкретного существующего расхода по ссылке из таблицы
	meter = get_object_or_404(MetersData, pk = meter_id)
	if request.method == 'POST':
		form = MetersForm(request.POST, instance = meter) # связывание данных формы с данными конкретного экземпляра модели  (изменение)
		form.save() 
		return HttpResponseRedirect(reverse('meters:index', ))
	else:
		form = MetersForm(instance = meter) # создание формы для изменения существующего расхода
		context = {'form' : form}
		return render(request, 'meters/addmetersdata.html', context)


@login_required(login_url='/table/')
def delete_meter(request, meter_id):
	meter = get_object_or_404(MetersData, pk = meter_id)
	meter.delete()
	return HttpResponseRedirect(reverse('meters:index', ))

@login_required(login_url='/table/')
def get_text_to_send(request): # формирование текста для отправки показаний счетчиков
	with connection.cursor() as cursor:
		sql = """
		SELECT * 
		FROM meters_metersdata
		WHERE date_meter = (SELECT MAX(date_meter) FROM meters_metersdata)
		"""
		cursor.execute(sql)
		meter = dictfetchall(cursor)
	context = {'meter':meter[0]}
	return render(request, 'meters/texttosend.html', context)

meters/templates/meters/addmetersdata.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>Показания счетчиков</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>

<a href="{% url 'table:main' %}">Вернуться на главную</a></br></br>
<form action="" method="post">
{% csrf_token %}
    {{ form.as_p }}
<input type="submit" name = "save" value="Сохранить" />
</form>

meters/templates/meters/meterscurrentyear.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>ФИНАНСЫ</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>


<a href="{% url 'table:main' %}">На главную</a></br></br>
<a href="{% url 'meters:addmetersdata' %}">Добавить показания счетчиков</a></br></br>
<a href="{% url 'meters:texttosend' %}">Сформировать текст для отправки показаний</a></br></br>
<table border="1" width="50%">
<caption><b>Показания счетчиков в текущем году</b></caption>
	<tr>
		<th>Дата снятия показаний</th>
		<th>Холодная вода</th>
		<th>Горячая вода</th>
		<th>Электроэнергия в квартире</th>
		<th>Электроэнергия в подсобном помещении</th>
		<th>Примечание</th>
		<th></th>
	</tr>
	{% for meter in meters_current_year %}
	<tr>
		<td><a href="{% url 'meters:getchangemeter' meter.id %}">{{meter.date_meter|date:"d.m.Y"}}</a></td>
		<td>{{meter.cold_water}}</td>
		<td>{{meter.hot_water}}</td>
		<td>{{meter.electricity_apartment}}</td>
		<td>{{meter.electricity_storeroom}}</td>
		<td>{{meter.note}}</td>
		<td ><a href="{% url 'meters:deletemeter' meter.id %}">Удалить</a></td>
	</tr>
	{% endfor %} 
</table>

meters/templates/meters/texttosend.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>Показания счетчиков</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>

<a href="{% url 'table:main' %}">Вернуться на главную</a></br></br>
<h3>Скопируйте текст в буфер обмена и отправьте на адрес comm.ch@yandex.ru</h3>
<p>Собственник: Седов Виктор Валентинович</p>
<p>Адрес: ул.С.Преминина, д.14, кв.213</p>
<p>Холодная вода = {{meter.cold_water}}</p>
<p>Горячая вода = {{meter.hot_water}}</p>
<p>Электроэнергия = {{meter.electricity_apartment}}</p>
<p>Электроэнергия подсоб.помещ. = {{meter.electricity_storeroom}}</p>
<p>Телефон для связи:89535037106</p>

meters/templates/meters/еучеещыутв.html
<table width="100%" bgcolor="#A5B0A9">
    <tr>
        <td> <<h1>Показания счетчиков</h1></td>
        <td align="right" valign="top"> <a href="{% url 'table:auth_logout' %}">Выйти</a> </td>
    </tr>
</table>

<a href="{% url 'table:main' %}">Вернуться на главную</a></br></br>
<h3>Скопируйте текст в буфер обмена и отправьте на адрес comm.ch@yandex.ru</h3>
<p>Собственник: Седов Виктор Валентинович</p>
<p>Адрес: ул.С.Преминина, д.14, кв.213</p>
<p>Холодная вода = {{meter.cold_water}}</p>
<p>Горячая вода = {{meter.hot_water}}</p>
<p>Электроэнергия = {{meter.electricity_apartment}}</p>
<p>Электроэнергия подсоб.помещ. = {{meter.electricity_storeroom}}</p>
<p>Телефон для связи:89535037106</p>